### ISSUE TITLE
Active directory authentication

### ISSUE THREAD

**Issue by vm00001** [instaclustr/cassandra-ldap#1]
When using the ldap module against Active Directory we are getting a "javax.naming.CommunicationException: Connection reset" after 15 minutes of idle connection.

**Comment by kgreav** [comment]
Sounds like AD is killing the persistent LDAP connection.
I guess as a work-around we could refresh the connection periodically, or maybe there's some timeout you can set on the AD side?

**Comment by smiklosovic** [comment]
Hi @vm00001 

Maybe this is helpful for OpenLDAP?  (1)

> 5.2.1.1. olcIdleTimeout: <integer>
Specify the number of seconds to wait before forcibly closing an idle client connection. A value of 0, the default, disables this feature.

Please let us know if it helped.

(1) https://www.openldap.org/doc/admin24/guide.html#Configuration%20Directives
