### ISSUE TITLE
AuthenticationFailed

### ISSUE THREAD

**Issue by loayNaser** [instaclustr/cassandra-ldap#12]
Hi, 
im using cassandra : 3.11.4 and ldap image osixia/openldap
i followed the steps in the readme the ldap jar in cassandra lib and the ldap property in the cassandra conf and the Dcassandra.ldap.properties.file and CLASSPATH is updated accordingly 

after cassandra is up i try to connect to cqlsh using : cqlsh -u cn=admin,dn=example,dn=org
and i get 
Connection error: ('Unable to connect to any servers', {'127.0.0.1': AuthenticationFailed('Failed to authenticate to 127.0.0.1: Error from server: code=0100 [Bad credentials] message="cn=admin,dn=example,dn=org is not permitted to log in"',)})
any advise ?!

im working with single node

**Comment by smiklosovic** [comment]
Hey, have you created admin:admin in LDAP itself? Are you able to login into LDAP directly?
