### ISSUE TITLE
Could not authenticate to the LDAP directory

### ISSUE THREAD

**Issue by epasham** [instaclustr/cassandra-ldap#6]
we are having strange issue. 2-3 users are able to login with LDAP authentication. 5 New users are created in the database but they are not able to login. getting the below error

Connection error: ('Unable to connect to any servers', {'10.221.6.28': AuthenticationFailed('Failed to authenticate to 10.221.6.28: Error from server: code=0000 [Server error] message="java.lang.SecurityException: Could not authenticate to the LDAP directory"',)})

**Comment by slater-ben** [comment]
Hi, 

Just letting you know that we have seen this but it will probably be a few weeks before anyone has time to look at it.

In the meantime, if you find any more info through debugging then let us know.

Cheers
Ben

**Comment by PabloL007** [comment]
Hello @slater-ben , we're experiencing the problem as well, can you share any update on when we can expect to see a fix?

**Comment by smiklosovic** [comment]
hi @epasham 

Can you please provide more information as what Cassandra version and branch of this repository you are using and what LDAP server you are running, please? The more information you share, the higher probability it will be solved to your satisfaction.

**Comment by smiklosovic** [comment]
@epasham @PabloL007 could you please try the branch 3.11? The reason why it can not connect will be more descriptive as the exception message is included as well.

Please follow the readme where is the example how the integration with OpenLDAP server in Docker in connection with Cassandra is shown.
